Implemented "/login" and "/users" API endpoints
AUA-CS322/aua-cs322-team-b-server pull request #1
Opened 2020-11-20 15:07 UTC by hovtoros

Implemented "/login" and "/users" API endpoints to support user login and users list retrieval functionality correspondingly (tests are missing). Restructured project files organization pattern, to be more web project friendly.

2020-11-20 16:16 UTC, hammerhg requested changes
What are all these empty files here? Like `src/utils/logger/logger.py`

2020-11-20 16:16 UTC, hammerhg commented on src/app.py
> +app.config['JWT_SECRET_KEY'] = 'C1CF4B7DC4C4153KNJ54E4F55OCA4'
Can we hide this from the source code?

2020-11-20 16:16 UTC, hammerhg commented on src/api/controllers/users_controller.py
> +@users_controller.route('/users', methods=['GET'])
What is the intention to have such method?

2020-11-20 16:16 UTC, hammerhg commented on src/api/controllers/home_controller.py
> +    return 'Welcome to AUA org-chart'
I guess this is just a placeholder

2020-11-20 16:16 UTC, hammerhg commented on src/api/controllers/account_controller.py
> +    repository = UserRepository()
I am not very experienced in Python, but wouldn't it be better to init this once outside of the the login method?

2020-11-20 16:16 UTC, hammerhg commented on .idea/misc.xml
> -  <component name="ProjectRootManager" version="2" project-jdk-name="Python 3.7 (Deep_Learning)" project-jdk-type="Python SDK" />
Why did you commit PyCharm project files?

Add it to .gitignore and do not commit, it will break the project for others when they commit their versions. and these files change all the time.

2020-11-21 05:21 UTC, hovtoros commented on src/api/controllers/users_controller.py
> +@users_controller.route('/users', methods=['GET'])
It is implemented for testing purposes, where it is possible to request an endpoint which is already protected resource (@jwt_required stands for that), and see wհether the authentication works correctly in general, considering the auth tokens provided by '/login' api. The implementation of this method may be eliminated or extended in further development.

2020-11-21 05:24 UTC, hovtoros commented on src/api/controllers/home_controller.py
> +    return 'Welcome to AUA org-chart'
Yes, this API endpoint doesn't have much sense of functionality, except for testing the server run in general, e.g. if the default route works, than the server is running.

2020-11-21 07:54 UTC, hovtoros commented on .idea/misc.xml
> -  <component name="ProjectRootManager" version="2" project-jdk-name="Python 3.7 (Deep_Learning)" project-jdk-type="Python SDK" />
Resolved the issue under the commit 024ab05903509496488bff7021a7eeb7b4ba5449.

2020-11-21 07:55 UTC, hovtoros commented on src/api/controllers/account_controller.py
> +    repository = UserRepository()
Resolved the issue under the commit effb938bc0a54665b2f89a90e06dcf938df86f3d.

2020-11-21 07:59 UTC, hovtoros commented on src/app.py
> +app.config['JWT_SECRET_KEY'] = 'C1CF4B7DC4C4153KNJ54E4F55OCA4'
Resolved the issue under the commit b5b46491e9fb037b735ee2e16ea4fbdf063a4b6c.
@hammerhg, now the secret key is stored under the file **.env** at the root folder of the project sources. If this doesn't correspond to the requirement, than I can add **.env** file to gitignore, so that each project runner will have to create personal .env file (the structure of .env is very simple, key-value principle in terms of python variables).

2020-11-21 08:07 UTC, hovtoros commented
> 
> 
> What are all these empty files here? Like `src/utils/logger/logger.py`
@hammerhg, all the **__init__.py** files are for the python packaging, which enables namespacing, e.g. for a class or script be available to other classes or scripts through a namespace link, as we are used to with Java, C#, etc. These files should be empty by default, but without them namespacing won't be possible.
Regarding **logger.py**, it is not empty, it has code inside.

2020-11-21 11:21 UTC, hammerhg approved these changes

2020-11-21 11:23 UTC, merged